[[main]]
  name = "Inicio"
  url = "#hero"
  weight = 10

[[main]]
  name = "Artículos"
  url = "#posts"
  weight = 20

[[main]]
  name = "Proyectos"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publicaciones"
  url = "#featured"
  weight = 40

[[main]]
  name = "Cursos"
  url = "courses/"
  weight = 50

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 60

